# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './design/forms/Laser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Laser(object):
    def setupUi(self, Laser):
        Laser.setObjectName("Laser")
        Laser.resize(1008, 865)
        Laser.setStyleSheet("QGroupBox::title {\n"
"    subcontrol-origin: padding;\n"
"    color: purple;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius:7px;\n"
"    min-height: 25px;\n"
"    background-color: palette(base);\n"
"    border: 1px outset gray;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border-color: navy;\n"
"}\n"
"\n"
"\n"
"QLabel {\n"
"    padding-left: 5px;    \n"
"}")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Laser)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(5)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.bnOpen = QtWidgets.QPushButton(Laser)
        self.bnOpen.setStyleSheet("QPushButton {\n"
"    min-width: 55px;\n"
"    background-color: rgb(211, 197, 255);\n"
"}")
        self.bnOpen.setObjectName("bnOpen")
        self.horizontalLayout_23.addWidget(self.bnOpen)
        self.bnSave = QtWidgets.QPushButton(Laser)
        self.bnSave.setStyleSheet("QPushButton {\n"
"    min-width: 55px;\n"
"    background-color: rgb(211, 197, 255);\n"
"}")
        self.bnSave.setObjectName("bnSave")
        self.horizontalLayout_23.addWidget(self.bnSave)
        self.bnInit = QtWidgets.QPushButton(Laser)
        self.bnInit.setStyleSheet("QPushButton {\n"
"    min-width: 55px;\n"
"    background-color: rgb(211, 197, 255);\n"
"}")
        self.bnInit.setObjectName("bnInit")
        self.horizontalLayout_23.addWidget(self.bnInit)
        self.bnClose = QtWidgets.QPushButton(Laser)
        self.bnClose.setStyleSheet("QPushButton {\n"
"    min-width: 55px;\n"
"    background-color: rgb(211, 197, 255);\n"
"}")
        self.bnClose.setObjectName("bnClose")
        self.horizontalLayout_23.addWidget(self.bnClose)
        self.bnSetting = QtWidgets.QPushButton(Laser)
        self.bnSetting.setStyleSheet("QPushButton {\n"
"    min-width: 55px;\n"
"    background-color: rgb(211, 197, 255);\n"
"}")
        self.bnSetting.setObjectName("bnSetting")
        self.horizontalLayout_23.addWidget(self.bnSetting)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_23)
        self.line_2 = QtWidgets.QFrame(Laser)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.groupBox = QtWidgets.QGroupBox(Laser)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: rgb(109, 127, 105);\n"
"    padding-left: 5px;\n"
"    max-width: 150px;    \n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lbPos = QtWidgets.QLabel(self.groupBox)
        self.lbPos.setStyleSheet("QLabel {\n"
"    background-color: rgb(228, 238, 255);\n"
"}")
        self.lbPos.setText("")
        self.lbPos.setObjectName("lbPos")
        self.horizontalLayout.addWidget(self.lbPos)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: rgb(109, 127, 105);\n"
"    padding-left: 5px;\n"
"    max-width: 150px;    \n"
"}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lsMarking = QtWidgets.QLabel(self.groupBox)
        self.lsMarking.setStyleSheet("QLabel {\n"
"    background-color: rgb(228, 238, 255);\n"
"}")
        self.lsMarking.setText("")
        self.lsMarking.setObjectName("lsMarking")
        self.horizontalLayout_2.addWidget(self.lsMarking)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setStyleSheet("QLabel {\n"
"    background-color: rgb(109, 127, 105);\n"
"    padding-left: 5px;\n"
"    max-width: 150px;    \n"
"}")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lbSpeed = QtWidgets.QLabel(self.groupBox)
        self.lbSpeed.setStyleSheet("QLabel {\n"
"    background-color: rgb(228, 238, 255);\n"
"}")
        self.lbSpeed.setText("")
        self.lbSpeed.setObjectName("lbSpeed")
        self.horizontalLayout_3.addWidget(self.lbSpeed)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setStyleSheet("QLabel {\n"
"    background-color: rgb(109, 127, 105);\n"
"    padding-left: 5px;\n"
"    max-width: 150px;    \n"
"}")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lbCount = QtWidgets.QLabel(self.groupBox)
        self.lbCount.setStyleSheet("QLabel {\n"
"    background-color: rgb(228, 238, 255);\n"
"}")
        self.lbCount.setText("")
        self.lbCount.setObjectName("lbCount")
        self.horizontalLayout_4.addWidget(self.lbCount)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setStyleSheet("QLabel {\n"
"    background-color: rgb(109, 127, 105);\n"
"    padding-left: 5px;\n"
"    max-width: 150px;    \n"
"}")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.lbMarkTime = QtWidgets.QLabel(self.groupBox)
        self.lbMarkTime.setStyleSheet("QLabel {\n"
"    background-color: rgb(228, 238, 255);\n"
"}")
        self.lbMarkTime.setText("")
        self.lbMarkTime.setObjectName("lbMarkTime")
        self.horizontalLayout_5.addWidget(self.lbMarkTime)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_14.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Laser)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gvPreview = View(self.groupBox_2)
        self.gvPreview.setStyleSheet("QGraphicsView {\n"
"    min-width: 300px;\n"
"    min-height: 200px;\n"
"}")
        self.gvPreview.setObjectName("gvPreview")
        self.verticalLayout_2.addWidget(self.gvPreview)
        self.horizontalLayout_14.addWidget(self.groupBox_2)
        self.horizontalLayout_14.setStretch(0, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.groupBox_4 = QtWidgets.QGroupBox(Laser)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setStyleSheet("QLabel {\n"
"    background-color: rgb(109, 127, 105);\n"
"    min-height: 30px;\n"
"    min-width: 100px;\n"
"}")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_20.addWidget(self.label_20)
        self.leMirrorX = QtWidgets.QLineEdit(self.groupBox_4)
        self.leMirrorX.setStyleSheet("QLineEdit {\n"
"    min-height: 25px;\n"
"    border-radius: 5px;\n"
"    border-bottom: 1px solid red;\n"
"    color: rgb(26, 49, 255);\n"
"}")
        self.leMirrorX.setText("")
        self.leMirrorX.setObjectName("leMirrorX")
        self.horizontalLayout_20.addWidget(self.leMirrorX)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setStyleSheet("QLabel {\n"
"    background-color: rgb(109, 127, 105);\n"
"    min-height: 30px;\n"
"    min-width: 100px;\n"
"}")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_21.addWidget(self.label_21)
        self.leMirrorY = QtWidgets.QLineEdit(self.groupBox_4)
        self.leMirrorY.setStyleSheet("QLineEdit {\n"
"    min-height: 25px;\n"
"    border-radius: 5px;\n"
"    border-bottom: 1px solid red;\n"
"    color: rgb(26, 49, 255);\n"
"}")
        self.leMirrorY.setText("")
        self.leMirrorY.setObjectName("leMirrorY")
        self.horizontalLayout_21.addWidget(self.leMirrorY)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_21)
        self.bnMirrorMove = QtWidgets.QPushButton(self.groupBox_4)
        self.bnMirrorMove.setStyleSheet("QPushButton {\n"
"    min-width: 55px;\n"
"    background-color: rgb(211, 197, 255);\n"
"}")
        self.bnMirrorMove.setObjectName("bnMirrorMove")
        self.horizontalLayout_22.addWidget(self.bnMirrorMove)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(Laser)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setStyleSheet("QLabel {\n"
"    background-color: rgb(109, 127, 105);\n"
"    min-height: 30px;\n"
"    min-width: 100px;\n"
"}")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.cbEnt = QtWidgets.QComboBox(self.groupBox_3)
        self.cbEnt.setStyleSheet("QComboBox {\n"
"    min-width: 70px;\n"
"    min-height: 25px;\n"
"    border-radius: 5px;\n"
"    border-bottom: 1px solid red;\n"
"    color: rgb(26, 49, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top right;\n"
"    min-width: 25px;\n"
"    width: 15px;\n"
"}")
        self.cbEnt.setObjectName("cbEnt")
        self.horizontalLayout_12.addWidget(self.cbEnt)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setStyleSheet("QLabel {\n"
"    background-color: rgb(109, 127, 105);\n"
"    min-height: 30px;\n"
"    min-width: 100px;\n"
"}")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_11.addWidget(self.label_18)
        self.leEntText = QtWidgets.QLineEdit(self.groupBox_3)
        self.leEntText.setStyleSheet("QLineEdit {\n"
"    min-height: 25px;\n"
"    border-radius: 5px;\n"
"    border-bottom: 1px solid red;\n"
"    color: rgb(26, 49, 255);\n"
"}")
        self.leEntText.setText("")
        self.leEntText.setObjectName("leEntText")
        self.horizontalLayout_11.addWidget(self.leEntText)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_11)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setStyleSheet("QLabel {\n"
"    background-color: rgb(109, 127, 105);\n"
"    min-height: 30px;\n"
"    min-width: 100px;\n"
"}")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_13.addWidget(self.label_16)
        self.lbEntRect = QtWidgets.QLabel(self.groupBox_3)
        self.lbEntRect.setStyleSheet("QLabel {\n"
"    background-color: rgb(228, 238, 255);\n"
"}")
        self.lbEntRect.setText("")
        self.lbEntRect.setObjectName("lbEntRect")
        self.horizontalLayout_13.addWidget(self.lbEntRect)
        self.horizontalLayout_13.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setStyleSheet("QLabel {\n"
"    background-color: rgb(109, 127, 105);\n"
"    min-height: 30px;\n"
"    min-width: 100px;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.leEntX = QtWidgets.QLineEdit(self.groupBox_3)
        self.leEntX.setStyleSheet("QLineEdit {\n"
"    min-height: 25px;\n"
"    border-radius: 5px;\n"
"    border-bottom: 1px solid red;\n"
"    color: rgb(26, 49, 255);\n"
"}")
        self.leEntX.setText("")
        self.leEntX.setObjectName("leEntX")
        self.horizontalLayout_6.addWidget(self.leEntX)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setStyleSheet("QLabel {\n"
"    background-color: rgb(109, 127, 105);\n"
"    min-height: 30px;\n"
"    min-width: 100px;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.leEntY = QtWidgets.QLineEdit(self.groupBox_3)
        self.leEntY.setStyleSheet("QLineEdit {\n"
"    min-height: 25px;\n"
"    border-radius: 5px;\n"
"    border-bottom: 1px solid red;\n"
"    color: rgb(26, 49, 255);\n"
"}")
        self.leEntY.setText("")
        self.leEntY.setObjectName("leEntY")
        self.horizontalLayout_7.addWidget(self.leEntY)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setStyleSheet("QLabel {\n"
"    background-color: rgb(109, 127, 105);\n"
"    min-height: 30px;\n"
"    min-width: 100px;\n"
"}")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.leEntW = QtWidgets.QLineEdit(self.groupBox_3)
        self.leEntW.setStyleSheet("QLineEdit {\n"
"    min-height: 25px;\n"
"    border-radius: 5px;\n"
"    border-bottom: 1px solid red;\n"
"    color: rgb(26, 49, 255);\n"
"}")
        self.leEntW.setText("")
        self.leEntW.setObjectName("leEntW")
        self.horizontalLayout_8.addWidget(self.leEntW)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setStyleSheet("QLabel {\n"
"    background-color: rgb(109, 127, 105);\n"
"    min-height: 30px;\n"
"    min-width: 100px;\n"
"}")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.leEntH = QtWidgets.QLineEdit(self.groupBox_3)
        self.leEntH.setStyleSheet("QLineEdit {\n"
"    min-height: 25px;\n"
"    border-radius: 5px;\n"
"    border-bottom: 1px solid red;\n"
"    color: rgb(26, 49, 255);\n"
"}")
        self.leEntH.setText("")
        self.leEntH.setObjectName("leEntH")
        self.horizontalLayout_9.addWidget(self.leEntH)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.bnEntMark = QtWidgets.QPushButton(self.groupBox_3)
        self.bnEntMark.setChecked(False)
        self.bnEntMark.setAutoRepeat(False)
        self.bnEntMark.setAutoExclusive(False)
        self.bnEntMark.setFlat(False)
        self.bnEntMark.setObjectName("bnEntMark")
        self.horizontalLayout_16.addWidget(self.bnEntMark)
        self.bnEntRedLight = QtWidgets.QPushButton(self.groupBox_3)
        self.bnEntRedLight.setObjectName("bnEntRedLight")
        self.horizontalLayout_16.addWidget(self.bnEntRedLight)
        self.bnEntChangeText = QtWidgets.QPushButton(self.groupBox_3)
        self.bnEntChangeText.setObjectName("bnEntChangeText")
        self.horizontalLayout_16.addWidget(self.bnEntChangeText)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.bnEntMove = QtWidgets.QPushButton(self.groupBox_3)
        self.bnEntMove.setObjectName("bnEntMove")
        self.horizontalLayout_17.addWidget(self.bnEntMove)
        self.bnEntMoveSet = QtWidgets.QPushButton(self.groupBox_3)
        self.bnEntMoveSet.setObjectName("bnEntMoveSet")
        self.horizontalLayout_17.addWidget(self.bnEntMoveSet)
        self.bnEntGetHatch = QtWidgets.QPushButton(self.groupBox_3)
        self.bnEntGetHatch.setObjectName("bnEntGetHatch")
        self.horizontalLayout_17.addWidget(self.bnEntGetHatch)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.bnEntSetHatch = QtWidgets.QPushButton(self.groupBox_3)
        self.bnEntSetHatch.setObjectName("bnEntSetHatch")
        self.horizontalLayout_18.addWidget(self.bnEntSetHatch)
        self.bnEntSetPen = QtWidgets.QPushButton(self.groupBox_3)
        self.bnEntSetPen.setObjectName("bnEntSetPen")
        self.horizontalLayout_18.addWidget(self.bnEntSetPen)
        self.bnEntGetPen = QtWidgets.QPushButton(self.groupBox_3)
        self.bnEntGetPen.setObjectName("bnEntGetPen")
        self.horizontalLayout_18.addWidget(self.bnEntGetPen)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line = QtWidgets.QFrame(Laser)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtWidgets.QLabel(Laser)
        self.label_19.setStyleSheet("QLabel {\n"
"    min-height: 25px;\n"
"    background-color: rgb(109, 127, 105);\n"
"    padding-left: 2px;    \n"
"}")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.tePara = QtWidgets.QTextEdit(Laser)
        self.tePara.setObjectName("tePara")
        self.verticalLayout_4.addWidget(self.tePara)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)

        self.retranslateUi(Laser)
        QtCore.QMetaObject.connectSlotsByName(Laser)

    def retranslateUi(self, Laser):
        _translate = QtCore.QCoreApplication.translate
        Laser.setWindowTitle(_translate("Laser", "Form"))
        self.bnOpen.setText(_translate("Laser", "打开"))
        self.bnSave.setText(_translate("Laser", "保存"))
        self.bnInit.setText(_translate("Laser", "初始化"))
        self.bnClose.setText(_translate("Laser", "关闭"))
        self.bnSetting.setText(_translate("Laser", "设置"))
        self.groupBox.setTitle(_translate("Laser", "Info"))
        self.label.setText(_translate("Laser", "位置:"))
        self.label_3.setText(_translate("Laser", "是否标刻中:"))
        self.label_5.setText(_translate("Laser", "飞行速度:"))
        self.label_7.setText(_translate("Laser", "实体数量:"))
        self.label_9.setText(_translate("Laser", "上次标记时间:"))
        self.groupBox_2.setTitle(_translate("Laser", "Preview"))
        self.groupBox_4.setTitle(_translate("Laser", "振镜"))
        self.label_20.setText(_translate("Laser", "x:"))
        self.label_21.setText(_translate("Laser", "y:"))
        self.bnMirrorMove.setText(_translate("Laser", "移动"))
        self.groupBox_3.setTitle(_translate("Laser", "实体动作"))
        self.label_15.setText(_translate("Laser", "名称:"))
        self.label_18.setText(_translate("Laser", "内容:"))
        self.label_16.setText(_translate("Laser", "Rect:"))
        self.label_11.setText(_translate("Laser", "x:"))
        self.label_12.setText(_translate("Laser", "y:"))
        self.label_13.setText(_translate("Laser", "w:"))
        self.label_14.setText(_translate("Laser", "h:"))
        self.bnEntMark.setText(_translate("Laser", "标刻"))
        self.bnEntRedLight.setText(_translate("Laser", "红光预览"))
        self.bnEntChangeText.setText(_translate("Laser", "更改内容"))
        self.bnEntMove.setText(_translate("Laser", "移动"))
        self.bnEntMoveSet.setText(_translate("Laser", "移动&&设置"))
        self.bnEntGetHatch.setText(_translate("Laser", "获取填充参数"))
        self.bnEntSetHatch.setText(_translate("Laser", "设置填充"))
        self.bnEntSetPen.setText(_translate("Laser", "设置笔号"))
        self.bnEntGetPen.setText(_translate("Laser", "获取笔号参数"))
        self.label_19.setText(_translate("Laser", "参数:"))
from ui.ui import View
